'use strict';
const K='pmm_v2',$=s=>document.querySelector(s),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const CURS=['MXN','USD','EUR','COP','ARS','CLP','PEN','BRL'],LOC={MXN:'es-MX',USD:'en-US',EUR:'es-ES',COP:'es-CO',ARS:'es-AR',CLP:'es-CL',PEN:'es-PE',BRL:'pt-BR'};
const THEMES={'Verde Financiero':['#0e2721','#16372f','#eef3ec','#9bb5a8','#d9a93f','#5fcf9a','#27493f'],'Oscuro Neón':['#0b0b14','#151526','#f2f2ff','#8d8db3','#00f0ff','#ff2bd6','#2a2a45'],'Cyberpunk':['#14061f','#220a35','#fff4d6','#c19ad6','#fcee09','#ff3c6e','#3d1559'],'Claro Ejecutivo':['#f3f5f8','#ffffff','#18212f','#5b6778','#1b4f9c','#0d7a54','#d9dfe7'],'Pastel Soft':['#fbf4fa','#ffffff','#3b3050','#6f6288','#8a4fc4','#2f8f78','#eadcf0'],'Monocromático':['#111','#1c1c1c','#f0f0f0','#999','#fff','#bbb','#333'],'Océano':['#08202e','#0f3347','#e6f4f8','#8fb4c4','#4cc3e8','#7be0b8','#1d4b63'],'Atardecer':['#2a1220','#3d1b2e','#fff0e6','#d1a3a8','#ff9d4d','#ffd36e','#59283f'],'Bosque':['#16200f','#212f17','#eef4e2','#a5b88a','#c9e265','#78d17c','#36492a'],'Lavanda Noche':['#1a1530','#261f45','#f0ecff','#a99fd1','#b69cff','#7ee0d0','#3a3066'],'Arena':['#efe6d4','#faf5ea','#2b2418','#7d705a','#a4561c','#2f7a55','#d8cbb0']};
const LBL={need:'Necesario',ant:'Hormiga',inv:'Inversión',otro:'Otro'},PAYS=['Efectivo','Débito','Crédito'],ICAT=['Nómina','Ventas','Transferencia','Rendimientos','Otro'];
const D={v:2,profile:null,tx:[],cards:[],goals:[],ch:[],chBase:10,theme:'Verde Financiero',hide:false,fs:16,dense:false,h1:'14:00',h2:'20:00',tourDone:false,notif:false,last:'',lastBk:''};
let S=structuredClone(D);

/* ---------- utilidades ---------- */
const ymd=d=>d.toLocaleDateString('sv'),today=()=>ymd(new Date()),ds=k=>ymd(new Date(Date.now()-k*864e5));
const nowLocal=()=>new Date(Date.now()-new Date().getTimezoneOffset()*6e4).toISOString().slice(0,16);
const norm=s=>String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const cur=()=>S.profile?.cur||'MXN',$$=n=>new Intl.NumberFormat(LOC[cur()],{style:'currency',currency:cur()}).format(n),m=n=>`<span class="amt">${$$(n)}</span>`;
const sum=a=>a.reduce((s,t)=>s+t.amt,0),ex=(p='')=>S.tx.filter(t=>t.type==='exp'&&t.date.startsWith(p)),inc=p=>sum(S.tx.filter(t=>t.type==='inc'&&t.date.startsWith(p)));
const fld=(l,h)=>`<label><span class="k">${l}</span>${h}</label>`,scc=s=>s>=70?'n':s>=40?'i':'a',col=d=>d<=3?'a':d<=7?'i':'n';
let toastT;const toast=t=>{$('#toast').textContent=t;clearTimeout(toastT);toastT=setTimeout(()=>$('#toast').textContent='',3000)};
let lock=false;
function modal(h,l){lock=!!l;const o=$('#modal');o.innerHTML=h?`<div class="ov"><div class="pn" role="dialog" aria-modal="true" tabindex="-1">${h}</div></div>`:'';if(h)(o.querySelector('input,button')||o).focus()}

/* ---------- persistencia (localStorage + IndexedDB) ---------- */
function idb(mode,v){return new Promise(r=>{try{const q=indexedDB.open('pmm',1);q.onupgradeneeded=()=>q.result.createObjectStore('s');q.onerror=()=>r();q.onsuccess=()=>{const s=q.result.transaction('s',mode==='get'?'readonly':'readwrite').objectStore('s'),x=mode==='put'?s.put(v,'d'):mode==='del'?s.delete('d'):s.get('d');x.onsuccess=()=>r(x.result);x.onerror=()=>r()}}catch{r()}})}
const save=()=>{const j=JSON.stringify(S);try{localStorage.setItem(K,j)}catch{}idb('put',j)};
function sane(o){const n=structuredClone(D),num=x=>Number.isFinite(+x)?+x:0,str=(x,l=120)=>String(x??'').slice(0,l),cl=x=>Math.min(31,Math.max(1,Math.round(+x)||1)),tm=(x,d)=>/^\d\d:\d\d$/.test(x)?x:d;
 if(o.profile?.name)n.profile={name:str(o.profile.name,30),cur:CURS.includes(o.profile.cur)?o.profile.cur:'MXN'};
 const oc=Array.isArray(o.cards)?o.cards:[],ids=[];
 n.cards=oc.map((c,i)=>{const id=/^[\w-]+$/.test(c.id||'')?c.id:uid();ids[i]=id;return{id,name:str(c.name,40),limit:Math.max(1,num(c.limit)),rate:num(c.rate),cut:cl(c.cut),due:cl(c.due)}});
 const cid=v=>n.cards.some(c=>c.id===v)?v:(v!==''&&ids[+v]&&!oc[+v]?.id?ids[+v]:'');
 n.tx=(Array.isArray(o.tx)?o.tx:[]).filter(t=>['exp','inc','pay'].includes(t.type)&&num(t.amt)>0&&/^\d{4}-\d\d-\d\d/.test(t.date)).map(t=>({id:uid(),type:t.type,amt:num(t.amt),desc:str(t.desc),cls:LBL[t.cls]?t.cls:'otro',pay:PAYS.includes(t.pay)?t.pay:'Efectivo',card:t.type==='inc'?'':cid(t.card),date:str(t.date,16),note:str(t.note,200),cat:str(t.cat,30),late:!!t.late}));
 n.goals=(Array.isArray(o.goals)?o.goals:[]).filter(g=>g.n&&num(g.t)>0).map(g=>({id:uid(),n:str(g.n,40),t:num(g.t),s:Math.max(0,num(g.s))}));
 n.ch=[...new Set((Array.isArray(o.ch)?o.ch:[]).map(Number).filter(w=>w>=1&&w<=52))];n.chBase=Math.max(1,num(o.chBase)||10);
 n.theme=THEMES[o.theme]?o.theme:D.theme;n.hide=!!o.hide;n.fs=Math.min(20,Math.max(13,num(o.fs)||16));n.dense=!!o.dense;n.h1=tm(o.h1,'14:00');n.h2=tm(o.h2,'20:00');n.tourDone=!!o.tourDone;n.notif=!!o.notif;n.lastBk=str(o.lastBk,10);return n}

/* ---------- motor inteligente ---------- */
const KW={need:'renta alquiler luz agua gas internet despensa super supermercado mercado transporte camion gasolina metro uber pasaje salud medicina medicamento farmacia doctor dentista escuela colegiatura comida tortillas leche huevo pan verdura fruta carne pollo',
ant:'botana botanas papas cafe antojo refresco dulce dulces netflix spotify disney juego videojuego cine snack helado cerveza galleta chicle starbucks suscripcion ubereats rappi pizza hamburguesa tacos',
inv:'libro libros gimnasio gym curso cursos ahorro herramienta herramientas deporte taller certificacion inversion'};
const RX=Object.fromEntries(Object.entries(KW).map(([k,v])=>[k,new RegExp('\\b('+v.split(' ').join('|')+')\\b','g')]));
function classify(t){t=norm(t).replace(/uber eats/g,'ubereats');let b='otro',n=0;for(const k of['ant','inv','need']){const c=(t.match(RX[k])||[]).length;if(c>n){n=c;b=k}}return b}
const diag=c=>({need:['Gasto necesario','Cubre lo vital. Compara precios si puedes.'],inv:['Gasto Inteligente','Esto trabaja a tu favor a largo plazo.'],ant:['Gasto Prescindible','Pequeño hoy, grande al año. Mira el simulador en Más.'],otro:['Sin clasificar','Usa una palabra clave (despensa, café…) o elige la categoría a mano.']}[c]);
function parse(d){const x=d.match(/\$\s*(\d+(?:[.,]\d+)?)/)||d.match(/(\d+(?:[.,]\d+)?)\s*(?:pesos|mxn|usd|eur)/i);return x?parseFloat(x[1].replace(',','.')):0}
function score(d){const e=ex(d);if(!e.length)return 90;const t=sum(e),p=c=>sum(e.filter(x=>x.cls===c))/t,mo=d.slice(0,7),b=inc(mo)/30;
 let s=100-60*p('ant')-10*p('otro')+15*p('inv')-(b&&t>b*1.3?Math.min(25,25*(t/b-1.3)):0)+(b&&sum(ex(mo))<b*24?5:0);return Math.max(0,Math.min(100,Math.round(s)))}
function bal(){const e=ex(),pay=sum(S.tx.filter(t=>t.type==='pay'));return{inc:inc(''),ex:sum(e),liq:inc('')-sum(e.filter(t=>t.pay!=='Crédito'))-pay,debt:sum(e.filter(t=>t.pay==='Crédito'))-pay}}
function chk(n){const run=(L,fin)=>{let q=0;const d={},ck=()=>{if(q<-.005)return `Fondos insuficientes: te faltarían ${$$(-q)}.`;for(const c of S.cards){if(d[c.id]>c.limit+.005)return `Excede el límite de ${c.name} por ${$$(d[c.id]-c.limit)}.`;if(d[c.id]<-.005)return 'El pago supera la deuda de la tarjeta.'}};
 for(const t of L.slice().sort((a,b)=>a.date.localeCompare(b.date))){if(t.type==='inc')q+=t.amt;else if(t.type==='pay'){q-=t.amt;d[t.card]=(d[t.card]||0)-t.amt}else if(t.pay==='Crédito')d[t.card]=(d[t.card]||0)+t.amt;else q-=t.amt;if(!fin){const e=ck();if(e)return e}}return fin?ck():null};
 return run(n,!!run(S.tx))}
const when=p=>$('#'+p+'r').checked?$('#'+p+'f').value:nowLocal();
function add(t,f){if(!t.date)return f('Elige fecha y hora.'),false;if(t.date>nowLocal())return f('No puedes registrar algo en una hora que aún no llega.'),false;const e=chk([...S.tx,t]);if(e)return f(e),false;S.tx.push(t);save();return true}
const cdebt=c=>sum(ex().filter(t=>t.pay==='Crédito'&&t.card===c.id))-sum(S.tx.filter(t=>t.type==='pay'&&t.card===c.id));
function daysTo(day){const n=new Date(),t=new Date(n.getFullYear(),n.getMonth(),n.getDate()),at=(y,mo)=>new Date(y,mo,Math.min(day,new Date(y,mo+1,0).getDate()));let d=at(t.getFullYear(),t.getMonth());if(d<t)d=at(t.getFullYear(),t.getMonth()+1);return Math.round((d-t)/864e5)}
const wk=o=>ex().filter(t=>{const d=t.date.slice(0,10);return d>ds(7*(o+1))&&d<=ds(7*o)});
function sm(e){const t=sum(e),p=c=>t?Math.round(100*sum(e.filter(x=>x.cls===c))/t):0;return{t,need:p('need'),ant:p('ant'),inv:p('inv')}}
const rec=(s,sc)=>!s.t?'Día sin gastos: excelente. Mantén el ritmo.':s.ant>30?'Mañana cambia un gasto hormiga por una opción casera.':sc>=80?'Buen control. Aparta una parte para tu meta de ahorro.':'Define un tope diario y revisa lo que quedó sin clasificar.';
const waText=k=>{const s=sm(k==='w'?wk(0):ex(today())),sc=score(today());return `🪙 *Porte-Monnaie Malin* — ${k==='w'?'últimos 7 días':today()}\n💸 Gastado: ${$$(s.t)}\n✅ Necesario: ${s.need}%\n🐜 Hormiga: ${s.ant}%\n📈 Inversión: ${s.inv}%\n⭐ Score de hoy: ${sc}/100\n💡 ${rec(s,sc)}`};

/* ---------- vistas ---------- */
let tab='home',sub='w',hm=today().slice(0,7),Q='',FT='all',fb='',charts=[],ts=0;
const TABS=[['home','Inicio','🏠'],['movs','Movs','🧾'],['cards','Tarjetas','💳'],['stats','Análisis','📊'],['tools','Más','🧰'],['set','Ajustes','⚙️']];
const optsL=sel=>Object.entries(LBL).map(([k,v])=>`<option value="${k}" ${k===sel?'selected':''}>${v}</option>`).join('');
const row=t=>`<div class="row"><div><div>${esc(t.desc)}</div><div class="extra"><span class="tag">${t.type==='exp'?LBL[t.cls]+' · '+t.pay:t.type==='inc'?'Ingreso'+(t.cat?' · '+esc(t.cat):''):'Pago tarjeta'}</span> <span class="k">${esc(t.date.replace('T',' '))}</span>${t.late?' <span class="tag">olvidado</span>':''}${t.note?`<div class="k">📝 ${esc(t.note)}</div>`:''}${t.type==='exp'?`<select class="mini" data-c="recls" data-i="${t.id}" aria-label="Reclasificar">${optsL(t.cls)}</select>`:''}</div></div><div class="r"><b class="${t.type==='inc'?'n':'a'} amt">${t.type==='inc'?'+':'−'}${$$(t.amt)}</b> <button data-a="del" data-i="${t.id}" aria-label="Eliminar movimiento">✕</button></div></div>`;
function alerts(){return S.cards.flatMap(c=>[['Corte',c.cut],['Pago',c.due]].map(([n,d])=>[n,daysTo(d),c.name])).filter(a=>a[1]<=5).map(a=>`<div class="msg ${a[0]==='Pago'?'bad':''}">${a[0]} de <b>${esc(a[2])}</b> ${a[1]?`en ${a[1]} día${a[1]>1?'s':''}`:'<b>hoy</b>'}</div>`).join('')}
const V={
home(){const b=bal(),sc=score(today());return `<h2>Hola, ${esc(S.profile.name)}</h2>${alerts()}
<div class="g"><div class="pn"><div class="k">Liquidez disponible</div><div class="num">${m(b.liq)}</div><div class="k">Ingresos − efectivo/débito − pagos de tarjeta</div></div><div class="pn"><div class="k">Ingresos</div><div class="num n">${m(b.inc)}</div></div><div class="pn"><div class="k">Gastos (incl. crédito)</div><div class="num a">${m(b.ex)}</div></div><div class="pn"><div class="k">Deuda en crédito</div><div class="num i">${m(Math.max(0,b.debt))}</div></div></div>
<div class="pn"><div class="k">Score de hoy</div><div class="sc ${scc(sc)}">${sc}<small class="k"> / 100</small></div><p><button data-a="close">Cierre del día</button></p></div>
<div class="pn"><h3>− Gasto <span class="k">Disponible ${m(b.liq)} · hora automática</span></h3><div class="f">${fld('Descripción','<input id="ed" placeholder="$28 en papas de la tienda" autocomplete="off">')}${fld('Monto (opcional si va con $ en la descripción)','<input id="ea" type="number" inputmode="decimal" step="0.01" min="0">')}${fld('Pago',`<select id="ep" data-c="pay">${PAYS.map(p=>`<option>${p}</option>`).join('')}</select>`)}<span id="cw" hidden>${fld('Tarjeta',`<select id="ec">${S.cards.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')||'<option value="">Sin tarjetas</option>'}</select>`)}</span><label style="grid-column:1/-1"><input type="checkbox" id="er" data-c="retro"> Gasto no registrado (lo olvidé anotar)</label><span id="ew" hidden>${fld('¿Cuándo fue?',`<input id="ef" type="datetime-local" max="${nowLocal()}" value="${nowLocal()}">`)}</span>${fld('Categoría',`<select id="ek"><option value="">Automática</option>${optsL()}</select>`)}${fld('Nota / ticket','<input id="en" maxlength="200">')}</div><button class="p" data-a="addExp">− Gasto</button><div id="fb" aria-live="polite">${fb}</div></div>
<div class="pn"><h3>+ Ingreso <span class="k">hora automática</span></h3><div class="f">${fld('Concepto','<input id="id" maxlength="60">')}${fld('Monto','<input id="ia" type="number" inputmode="decimal" step="0.01" min="0">')}${fld('Categoría',`<select id="ic">${ICAT.map(c=>`<option>${c}</option>`).join('')}</select>`)}<label style="grid-column:1/-1"><input type="checkbox" id="ir" data-c="retro"> Ingreso no registrado (lo olvidé anotar)</label><span id="iw" hidden>${fld('¿Cuándo fue?',`<input id="if" type="datetime-local" max="${nowLocal()}" value="${nowLocal()}">`)}</span></div><button class="p" data-a="addInc">+ Ingreso</button></div>
<div class="pn"><h3>Recientes</h3>${S.tx.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(row).join('')||'<p class="k">Aún no hay movimientos.</p>'}</div>`},
movs(){return `<h2>Movimientos</h2><div class="f"><input type="search" value="${esc(Q)}" placeholder="Buscar…" data-c="q" aria-label="Buscar">${`<select data-c="ft" aria-label="Filtrar">${[['all','Todos'],['exp','Gastos'],['inc','Ingresos'],['pay','Pagos']].map(([k,v])=>`<option value="${k}" ${k===FT?'selected':''}>${v}</option>`).join('')}</select>`}</div><div class="pn" id="lst">${list()}</div>`},
cards(){return `<h2>Tarjetas de crédito</h2><div class="pn"><div class="f">${fld('Nombre','<input id="cn" maxlength="40">')}${fld('Límite','<input id="cl" type="number" min="1">')}${fld('Tasa anual %','<input id="cr" type="number" step="0.1" min="0">')}${fld('Día de corte','<input id="cc" type="number" min="1" max="31">')}${fld('Día límite de pago','<input id="cd" type="number" min="1" max="31">')}</div><button class="p" data-a="addCard">Guardar tarjeta</button></div>`+
 (S.cards.map(c=>{const d=cdebt(c),dc=daysTo(c.cut),dd=daysTo(c.due);return `<div class="pn"><h3>${esc(c.name)} <span class="tag">${c.rate}% anual</span></h3><div class="row"><span>Deuda</span><b class="i">${m(Math.max(0,d))}</b></div><div class="row"><span>Disponible</span>${m(Math.max(0,c.limit-d))}</div><div class="bar"><i style="width:${Math.min(100,100*d/c.limit)}%;background:var(--bad)"></i></div><div class="row"><span>Interés mensual estimado</span>${m(Math.max(0,d)*c.rate/1200)}</div><div class="row"><span>Corte en</span><b class="${col(dc)}">${dc} días</b></div><div class="row"><span>Pago límite en</span><b class="${col(dd)}">${dd} días</b></div><p><button data-a="payCard" data-i="${c.id}">Registrar pago</button> <button data-a="delCard" data-i="${c.id}">Eliminar</button></p></div>`}).join('')||'<p class="k">Agrega una tarjeta para ver fechas, deuda e intereses.</p>')},
stats(){const[y,mo]=hm.split('-').map(Number),n=new Date(y,mo,0).getDate(),off=(new Date(y,mo-1,1).getDay()+6)%7,vals=Array.from({length:n},(_,i)=>sum(ex(`${hm}-${String(i+1).padStart(2,'0')}`))),ref=inc(hm)/30||sum(vals)/Math.max(1,vals.filter(Boolean).length)||1,cell=v=>!v?'var(--bg)':v<=ref*.7?'var(--ok)':v<=ref*1.2?'var(--wr)':'var(--bad)';
 return `<h2>Análisis</h2><div class="pn"><div class="row"><h3>Mapa de calor</h3><input type="month" value="${hm}" data-c="hm" style="width:auto" aria-label="Mes"></div><div class="hm">${['L','M','X','J','V','S','D'].map(d=>`<span>${d}</span>`).join('')}${'<span></span>'.repeat(off)}${vals.map((v,i)=>`<button data-a="day" data-i="${i+1}" style="background:${cell(v)};${v?'':'color:var(--mu)'}" aria-label="Día ${i+1}">${i+1}</button>`).join('')}</div><p class="k">Referencia diaria ${m(ref)} · verde ≤70% · amarillo ≤120% · rojo más. Toca un día para ver su monto.</p></div>
<div class="pn"><h3>Gasto por categoría (${hm})</h3><div class="cv"><canvas id="ch1" role="img" aria-label="Gasto por categoría"></canvas></div></div><div class="pn"><h3>Ingresos vs gastos, 6 meses</h3><canvas id="ch2" role="img" aria-label="Comparativo mensual"></canvas></div>
<div class="tabs"><button data-a="sub" data-i="w" class="${sub==='w'?'on':''}">Semanal</button><button data-a="sub" data-i="m" class="${sub==='m'?'on':''}">Mensual</button></div>${sub==='w'?weekly():monthly()}${subs()}`},
tools(){return `<h2>Más herramientas</h2><div class="pn"><h3>Mercado y cripto</h3><div id="mk"></div><p class="k">Datos de CoinGecko. Consultarlo expone tu IP a ese servicio; tus finanzas nunca se envían. <button data-a="mkr">Actualizar</button></p></div>
<div class="pn"><h3>Gastos hormiga anualizados</h3><div class="f"><input id="ha" type="number" value="28" data-c="sim" aria-label="Monto diario"><input id="hd" type="number" value="365" data-c="sim" aria-label="Días al año"></div><p>Al año: <b class="num a amt" id="ho"></b></p></div>
<div class="pn"><h3>Interés compuesto</h3><div class="f">${fld('Capital inicial','<input id="c0" type="number" value="0" data-c="sim">')}${fld('Aporte mensual','<input id="cm" type="number" value="500" data-c="sim">')}${fld('Rendimiento anual %','<input id="ci" type="number" value="8" step="0.1" data-c="sim">')}</div><div id="co"></div></div>
<div class="pn"><h3>Reto de 52 semanas</h3><p class="k">La semana N ahorras N × tu base. Toca para marcar.</p>${fld('Base semanal',`<input id="cb" type="number" min="1" value="${S.chBase}" data-c="cb">`)}<div id="chl"></div></div>
<div class="pn"><h3>Metas de ahorro</h3><div class="f">${fld('Meta','<input id="gn" maxlength="40" placeholder="Viaje">')}${fld('Objetivo','<input id="gt" type="number" min="1">')}</div><button class="p" data-a="addGoal">Crear meta</button><div id="gl"></div></div>`},
set(){return `<h2>Ajustes</h2><div class="pn"><h3>Perfil</h3><div class="f">${fld('Nombre',`<input value="${esc(S.profile.name)}" maxlength="30" data-c="name">`)}${fld('Moneda',`<select data-c="cur">${CURS.map(c=>`<option ${c===cur()?'selected':''}>${c}</option>`).join('')}</select>`)}</div></div>
<div class="pn"><h3>Apariencia</h3><div class="f">${fld('Tema',`<select data-c="theme">${Object.keys(THEMES).map(t=>`<option ${t===S.theme?'selected':''}>${t}</option>`).join('')}</select>`)}${fld('Tamaño de letra',`<input type="range" min="13" max="20" value="${S.fs}" data-c="fs">`)}</div><label><input type="checkbox" data-c="dense" ${S.dense?'checked':''}> Vista compacta en listas</label></div>
<div class="pn"><h3>Resúmenes</h3><div class="f">${fld('Medio día',`<input type="time" value="${S.h1}" data-c="h1">`)}${fld('Cierre diario',`<input type="time" value="${S.h2}" data-c="h2">`)}</div><p><button data-a="notif">${S.notif?'Notificaciones activas':'Activar notificaciones del navegador'}</button></p><p class="k">Los avisos aparecen mientras la app esté abierta o instalada; sin servidor no pueden dispararse con ella cerrada.</p></div>
<div class="pn"><h3>Exportar y respaldo</h3><p><button data-a="pdf">PDF del mes (${hm})</button> <button data-a="exp">Descargar copia (.json)</button></p>${fld('Importar copia (.json)','<input type="file" accept=".json,application/json" data-c="imp">')}<p class="k">Último respaldo: ${S.lastBk||'nunca'}. Tus datos viven solo en este dispositivo: respalda de vez en cuando.</p></div>
<div class="pn"><h3>Zona de riesgo</h3><button data-a="wipe">Borrar todos mis datos</button></div><p class="k" style="text-align:center">L'art de gérer votre argent en toute sagesse.</p>`}};
const list=()=>{const q=norm(Q),L=S.tx.filter(t=>(FT==='all'||t.type===FT)&&(!q||norm(t.desc+' '+t.note+' '+t.cat).includes(q))).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,300);return L.map(row).join('')||'<p class="k">Sin resultados.</p>'};
function weekly(){const tw=sum(wk(0)),lw=sum(wk(1)),df=lw?Math.round(100*(tw-lw)/lw):null,dow=Array(7).fill(0),all=ex(),tt=sum(all),dn=['domingo','lunes','martes','miércoles','jueves','viernes','sábado'];all.forEach(t=>dow[new Date(t.date.slice(0,10)+'T12:00').getDay()]+=t.amt);
 const mi=dow.indexOf(Math.max(...dow)),pc=tt?Math.round(100*(dow[mi]/(tt/7)-1)):0,top=Object.entries(LBL).map(([k,v])=>[v,sum(wk(0).filter(t=>t.cls===k))]).sort((a,b)=>b[1]-a[1])[0];
 return `<div class="pn"><h3>Análisis semanal</h3><p>Últimos 7 días: ${m(tw)} frente a ${m(lw)} ${df===null?'':`(<b class="${df>0?'a':'n'}">${df>0?'+':''}${df}%</b>)`}</p>${tt?`<p class="k">Los ${dn[mi]} gastas ${pc}% más que el promedio por día de la semana.</p>`:''}${tw?`<p class="k">Mayor fuga de la semana: ${top[0]} (${$$(top[1])}).</p>`:''}<button data-a="wa" data-i="w">Enviar semana por WhatsApp</button></div>`}
function monthly(){const[y,mo]=hm.split('-').map(Number),n=new Date(y,mo,0).getDate(),i=inc(hm),e=sum(ex(hm)),now=hm===today().slice(0,7),pj=e/(now?new Date().getDate():n)*n;
 return `<div class="pn"><h3>Balance de ${hm}</h3><div class="row"><span>Ingresos</span>${m(i)}</div><div class="row"><span>Gastos</span>${m(e)}</div><div class="row"><span>Ahorro</span><b class="${i-e>=0?'n':'a'}">${m(i-e)}</b></div>${now?`<div class="row"><span>Proyección a fin de mes</span><span>gasto ${m(pj)} · ahorro ${m(i-pj)}</span></div>`:''}<button data-a="pdf">Descargar estado de cuenta (PDF)</button></div>`}
function subs(){const g={};ex().forEach(t=>{const k=norm(t.desc).replace(/[\d$.,]+/g,'').replace(/\s+/g,' ').trim();if(k)(g[k]??=[]).push(t)});
 const r=Object.values(g).filter(a=>{if(a.length<2)return false;const d=a.map(t=>new Date(t.date.slice(0,10)+'T12:00')).sort((x,y)=>x-y);return d.slice(1).every((x,i)=>{const n=(x-d[i])/864e5;return n>=25&&n<=35})});
 return `<div class="pn"><h3>Posibles suscripciones</h3>${r.map(a=>`<div class="row"><span>${esc(a[0].desc)}</span><b class="i amt">~${$$(sum(a)/a.length)}/mes</b></div>`).join('')||'<p class="k">Sin cobros recurrentes detectados (se necesitan 2 cobros con ~1 mes de diferencia).</p>'}</div>`}
function drawCharts(){charts.forEach(c=>c.destroy());charts=[];if(!window.Chart)return;const cs=getComputedStyle(document.documentElement),g=k=>cs.getPropertyValue('--'+k).trim(),e=ex(hm),ks=Object.keys(LBL);Chart.defaults.color=g('ink');
 const c1=$('#ch1');if(c1)charts.push(new Chart(c1,{type:'doughnut',data:{labels:ks.map(k=>LBL[k]),datasets:[{data:ks.map(k=>sum(e.filter(t=>t.cls===k))),backgroundColor:[g('ok'),g('bad'),g('ac'),g('mu')],borderColor:g('pn')}]}}));
 const ms=[...Array(6)].map((_,i)=>ymd(new Date(+hm.slice(0,4),+hm.slice(5)-1-(5-i),1)).slice(0,7)),c2=$('#ch2');
 if(c2)charts.push(new Chart(c2,{type:'bar',data:{labels:ms,datasets:[{label:'Ingresos',data:ms.map(inc),backgroundColor:g('ac2')},{label:'Gastos',data:ms.map(p=>sum(ex(p))),backgroundColor:g('bad')}]},options:{scales:{x:{ticks:{color:g('mu')}},y:{ticks:{color:g('mu')}}}}}))}
function sim(){if(!$('#ha'))return;$('#ho').textContent=$$($('#ha').value*$('#hd').value);const c0=+$('#c0').value,c=+$('#cm').value,r=+$('#ci').value/1200;$('#co').innerHTML=[1,5,10].map(y=>{let v=c0;for(let i=0;i<y*12;i++)v=v*(1+r)+c*(1+r);return `<div class="row"><span>${y} año${y>1?'s':''}</span><b class="n amt">${$$(v)}</b></div>`}).join('')}
function chal(){const b=S.chBase;$('#chl').innerHTML=`<p>Ahorrado: <b class="n amt">${$$(S.ch.reduce((s,w)=>s+w*b,0))}</b> de ${$$(b*1378)}</p><div class="hm" style="grid-template-columns:repeat(13,1fr)">${Array.from({length:52},(_,i)=>`<button data-a="togW" data-i="${i+1}" aria-pressed="${S.ch.includes(i+1)}" style="background:${S.ch.includes(i+1)?'var(--ac2)':'var(--bg)'};font-size:.62rem">${i+1}</button>`).join('')}</div>`}
function goals(){$('#gl').innerHTML=S.goals.map(g=>`<div class="row"><div style="flex:1">${esc(g.n)} <span class="k amt">${$$(g.s)} / ${$$(g.t)}</span><div class="bar"><i style="width:${Math.min(100,100*g.s/g.t)}%"></i></div></div><span><button data-a="abonar" data-i="${g.id}">Abonar</button> <button data-a="delGoal" data-i="${g.id}" aria-label="Eliminar meta">✕</button></span></div>`).join('')||'<p class="k">Sin metas todavía.</p>'}
async function mkt(){const el=$('#mk');if(!el)return;const c=cur().toLowerCase();let ca;try{ca=JSON.parse(localStorage.getItem('pmm_mk'))}catch{}ca=ca&&ca.cur===cur()?ca:null;
 const show=(d,msg)=>{el.innerHTML=`<p class="k">${msg}</p>`+(d?[['bitcoin','BTC'],['ethereum','ETH'],['solana','SOL'],['tether','USD (vía USDT)']].map(([id,n])=>{const x=d[id];if(!x)return'';const ch=x[c+'_24h_change']||0;return `<div class="row"><span>${n}</span><span><b class="amt">${$$(x[c])}</b> <span class="${ch>=0?'n':'a'}">${ch>=0?'▲':'▼'} ${Math.abs(ch).toFixed(2)}%</span></span></div>`}).join(''):'')};
 show(ca&&ca.d,ca?'Mostrando último dato guardado…':'Cargando…');
 try{const r=await fetch(`https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,solana,tether&vs_currencies=${c}&include_24hr_change=true`);if(!r.ok)throw 0;const d=await r.json();try{localStorage.setItem('pmm_mk',JSON.stringify({cur:cur(),d}))}catch{}show(d,'Actualizado '+new Date().toLocaleTimeString())}
 catch{show(ca&&ca.d,ca?'Sin conexión: se muestra el último dato guardado.':'Sin conexión: precios no disponibles por ahora.')}}
const AFTER={stats:drawCharts,tools:()=>{sim();chal();goals();mkt()}};

/* ---------- render ---------- */
function theme(){const t=THEMES[S.theme]||THEMES[D.theme],r=document.documentElement;['bg','pn','ink','mu','ac','ac2','ln'].forEach((k,i)=>r.style.setProperty('--'+k,t[i]));const f=t[0].slice(1).replace(/^(.)(.)(.)$/,'$1$1$2$2$3$3');r.style.colorScheme=(parseInt(f.slice(0,2),16)*.3+parseInt(f.slice(2,4),16)*.59+parseInt(f.slice(4),16)*.11)<128?'dark':'light';r.style.fontSize=S.fs+'px';
 document.body.classList.toggle('blur',S.hide);document.body.classList.toggle('dense',S.dense);$('#eye').setAttribute('aria-pressed',S.hide);$('meta[name=theme-color]').content=t[0]}
function render(){theme();if(!S.profile){$('#top').innerHTML=$('#app').innerHTML=$('#nav').innerHTML='';$('#eye').hidden=true;return tour()}
 $('#eye').hidden=false;$('#nav').innerHTML=TABS.map(([k,l,i])=>`<button data-a="tab" data-i="${k}" class="${tab===k?'on':''}" ${tab===k?'aria-current="page"':''}><span aria-hidden="true">${i}</span>${l}</button>`).join('');
 $('#top').innerHTML=`<b>Porte-Monnaie Malin</b><small>${esc(S.profile.name)}</small>`;$('#app').innerHTML=V[tab]();AFTER[tab]?.()}
const TOUR=[['Tus datos, tu dispositivo','Todo se guarda solo en este navegador. Tus finanzas nunca viajan a ningún servidor.'],['Registra en segundos','Escribe «$28 en papas» y el monto y la categoría se completan solos.'],['Diagnóstico al instante','Cada gasto se marca como necesario, hormiga o inversión y suma a tu score diario.'],['Resúmenes y respaldo','Recibe un cierre diario, compártelo por WhatsApp, exporta PDF y guarda una copia .json.']];
function tour(){if(S.tourDone)return onboard();const[t,d]=TOUR[ts];modal(`<h3>${t}</h3><p>${d}</p><div class="row"><span class="k">${ts+1} de 4</span><span>${ts?'<button data-a="tb">Atrás</button> ':''}<button data-a="tskip">Saltar</button> <button class="p" data-a="tn">${ts<3?'Siguiente':'Empezar'}</button></span></div>`,1)}
function onboard(){modal(`<h3>¿Cómo quieres que te llamemos?</h3>${fld('Nombre o pseudónimo','<input id="pn" maxlength="30" autocomplete="nickname">')}${fld('Moneda',`<select id="pc">${CURS.map(c=>`<option>${c}</option>`).join('')}</select>`)}<p><button class="p" data-a="enter">Entrar</button></p>`,1)}

/* ---------- acciones ---------- */
const A={
tab(i){tab=i;fb='';render();scrollTo(0,0)},tn(){ts<3?(ts++,tour()):A.tskip()},tb(){ts--;tour()},tskip(){S.tourDone=true;save();onboard()},
enter(){const n=$('#pn').value.trim();if(!n)return $('#pn').focus();S.profile={name:n,cur:$('#pc').value};save();modal();render()},
eye(){S.hide=!S.hide;save();theme()},mclose(){modal()},ban(){$('#ban').innerHTML=''},
addExp(){const d=$('#ed').value.trim(),a=parseFloat($('#ea').value)||parse(d),f=h=>$('#fb').innerHTML=`<div class="msg bad">${h}</div>`;
 if(!d||!(a>0))return f('Escribe una descripción y un monto (ej. «$28 en papas»).');const pay=$('#ep').value,card=pay==='Crédito'?$('#ec').value:'';if(pay==='Crédito'&&!card)return f('Primero registra una tarjeta en la pestaña Tarjetas.');
 const cls=$('#ek').value||classify(d),[t,x]=diag(cls);if(!add({id:uid(),type:'exp',amt:a,desc:d,cls,pay,card,date:when('e'),late:$('#er').checked,note:$('#en').value.trim(),cat:''},f))return;fb=`<div class="msg"><b>${t}</b> — ${x} Score de hoy: ${score(today())}.</div>`;render()},
addInc(){const d=$('#id').value.trim(),a=parseFloat($('#ia').value);if(!d||!(a>0))return toast('Falta concepto o monto');if(add({id:uid(),type:'inc',amt:a,desc:d,cls:'otro',pay:'Efectivo',card:'',date:when('i'),late:$('#ir').checked,note:'',cat:$('#ic').value},toast)){toast('Ingreso registrado');render()}},
del(i){{const l=S.tx.filter(t=>t.id!==i),e=chk(l);if(e)return toast('No se puede eliminar: '+e);if(confirm('¿Eliminar este movimiento?')){S.tx=l;save();render()}}},
close(){const d=today(),s=sm(ex(d)),sc=score(d);modal(`<h3>Cierre del día</h3><p>Gastado: <b>${m(s.t)}</b></p><p>Necesario ${s.need}% · Hormiga ${s.ant}% · Inversión ${s.inv}%</p><div class="sc ${scc(sc)}">${sc}<small class="k"> / 100</small></div><div class="msg">${rec(s,sc)}</div><div class="row"><button class="p" data-a="wa" data-i="d">WhatsApp</button><button data-a="mclose">Cerrar</button></div>`);$('#ban').innerHTML=''},
wa(k){open('https://api.whatsapp.com/send?text='+encodeURIComponent(waText(k)),'_blank','noopener')},
addCard(){const n=$('#cn').value.trim(),l=+$('#cl').value,cl=x=>Math.min(31,Math.max(1,Math.round(+x)||1));if(!n||!(l>0))return toast('Falta nombre o límite');S.cards.push({id:uid(),name:n,limit:l,rate:+$('#cr').value||0,cut:cl($('#cc').value),due:cl($('#cd').value)});save();render()},
payCard(i){const a=parseFloat(prompt('Monto del pago:')||'');if(a>0){if(add({id:uid(),type:'pay',amt:a,desc:'Pago '+S.cards.find(c=>c.id===i).name,cls:'otro',pay:'Débito',card:i,date:nowLocal(),note:'',cat:''},toast))render()}},
delCard(i){const c=S.cards.find(x=>x.id===i);if(cdebt(c)>0.005)return toast('Salda la deuda antes de eliminarla');if(confirm('¿Eliminar tarjeta?')){S.cards=S.cards.filter(x=>x.id!==i);save();render()}},
sub(i){sub=i;render()},day(i){const d=`${hm}-${String(i).padStart(2,'0')}`;toast(`${d}: ${S.hide?'•••':$$(sum(ex(d)))}`)},
togW(i){i=+i;S.ch=S.ch.includes(i)?S.ch.filter(x=>x!==i):[...S.ch,i];save();chal()},
addGoal(){const n=$('#gn').value.trim(),t=+$('#gt').value;if(!n||!(t>0))return;S.goals.push({id:uid(),n,t,s:0});save();goals()},
abonar(i){const a=parseFloat(prompt('Monto a abonar:')||'');if(a>0){S.goals.find(g=>g.id===i).s+=a;save();goals()}},delGoal(i){if(confirm('¿Eliminar meta?')){S.goals=S.goals.filter(g=>g.id!==i);save();goals()}},
mkr(){mkt()},
async notif(){if(!('Notification'in window))return toast('Tu navegador no soporta notificaciones');S.notif=(await Notification.requestPermission())==='granted';save();render()},
exp(){const a=document.createElement('a');S.lastBk=today();save();a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,1)],{type:'application/json'}));a.download=`porte-monnaie-malin-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1e3)},
wipe(){if(!confirm('Se borrarán TODOS tus datos de este dispositivo. ¿Continuar?'))return;S=structuredClone(D);try{['pmm_v1',K,'pmm_mk'].forEach(k=>localStorage.removeItem(k))}catch{}idb('del');tab='home';render()},
pdf(){if(!window.jspdf)return toast('PDF no disponible');const{jsPDF}=window.jspdf,p=new jsPDF(),W=210,f=n=>n.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g,',')+' '+cur(),e=ex(hm),i=inc(hm),tot=sum(e),cl=s=>String(s).replace(/[^\x20-\xFF]/g,'');
 p.setFillColor(14,39,33);p.rect(0,0,W,34,'F');p.setTextColor(217,169,63);p.setFontSize(20);p.text('Porte-Monnaie Malin',14,16);p.setFontSize(10);p.setTextColor(238,243,236);p.text(cl(`Estado de cuenta ${hm} - ${S.profile.name}`),14,26);p.setTextColor(30);let y=48;p.setFontSize(12);
 [['Ingresos',f(i)],['Gastos',f(tot)],['Ahorro del mes',f(i-tot)],['Score financiero (hoy)',score(today())+'/100']].forEach(([a,b])=>{p.text(a,14,y);p.text(b,W-14,y,{align:'right'});y+=8});
 y+=4;p.setFontSize(13);p.text('Desglose por categoria',14,y);y+=8;p.setFontSize(10);
 Object.entries(LBL).forEach(([k,v])=>{const s=sum(e.filter(t=>t.cls===k)),pc=tot?s/tot:0;p.text(cl(v),14,y);p.setFillColor(95,207,154);p.rect(45,y-3.5,Math.max(.5,60*pc),4,'F');p.text(`${f(s)} (${Math.round(pc*100)}%)`,W-14,y,{align:'right'});y+=7});
 y+=6;p.setFontSize(13);p.text('Movimientos',14,y);y+=8;p.setFontSize(9);
 S.tx.filter(t=>t.date.startsWith(hm)).sort((a,b)=>a.date.localeCompare(b.date)).forEach(t=>{if(y>280){p.addPage();y=20}p.text(t.date.slice(0,10),14,y);p.text(cl(t.desc).slice(0,60),40,y);p.text((t.type==='inc'?'+':'-')+f(t.amt),W-14,y,{align:'right'});y+=6});p.save(`estado-${hm}.pdf`)}};
const C={
retro(el){$('#'+el.id[0]+'w').hidden=!el.checked},
q(el){Q=el.value;$('#lst').innerHTML=list()},ft(el){FT=el.value;$('#lst').innerHTML=list()},hm(el){hm=el.value||hm;render()},pay(el){$('#cw').hidden=el.value!=='Crédito'},
recls(el){const t=S.tx.find(x=>x.id===el.dataset.i);if(t){t.cls=el.value;save();toast('Reclasificado')}},
theme(el){S.theme=el.value;save();theme()},fs(el){S.fs=+el.value;save();theme()},dense(el){S.dense=el.checked;save();theme()},
name(el){if(el.value.trim()){S.profile.name=el.value.trim();save();$('#top').innerHTML=`<b>Porte-Monnaie Malin</b><small>${esc(S.profile.name)}</small>`}},cur(el){S.profile.cur=el.value;save();render()},
h1(el){S.h1=el.value||S.h1;save()},h2(el){S.h2=el.value||S.h2;save()},sim,cb(el){S.chBase=Math.max(1,+el.value||10);save();chal()},
imp(el){const f=el.files[0];if(!f)return;f.text().then(t=>{const n=sane(JSON.parse(t));if(!n.profile)throw 0;if(!confirm(`Se reemplazarán tus datos por la copia (${n.tx.length} movimientos). ¿Continuar?`))return;S=n;save();render();toast('Copia restaurada')}).catch(()=>toast('Archivo inválido'));el.value=''}};
document.addEventListener('click',e=>{if(e.target.classList.contains('ov')&&!lock)return modal();const el=e.target.closest('[data-a]');if(el)A[el.dataset.a]?.(el.dataset.i,el)});
['input','change'].forEach(ev=>document.addEventListener(ev,e=>{const el=e.target.closest('[data-c]');if(el)C[el.dataset.c]?.(el)}));
addEventListener('keydown',e=>{if(e.key==='Escape'&&!lock)modal()});

/* ---------- avisos programados (con la app abierta) ---------- */
setInterval(()=>{if(!S.profile)return;const t=new Date().toTimeString().slice(0,5),k=today()+t;if((t===S.h1||t===S.h2)&&S.last!==k){S.last=k;save();const s=sm(ex(today())),txt=`${t===S.h2?'Cierre diario':'Resumen de medio día'}: gastaste ${$$(s.t)} · hormiga ${s.ant}% · score ${score(today())}`;
 $('#ban').innerHTML=`<div class="msg"><b>${esc(txt)}</b> <button data-a="close">Ver detalle</button> <button data-a="ban" aria-label="Cerrar aviso">✕</button></div>`;if(S.notif&&Notification.permission==='granted')new Notification('Porte-Monnaie Malin',{body:txt})}},20000);

/* ---------- arranque ---------- */
(async()=>{let r;try{r=localStorage.getItem(K)||localStorage.getItem('pmm_v1')}catch{}r=r||await idb('get');if(r)try{S=sane(JSON.parse(r))}catch{}
 navigator.storage?.persist?.();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>{});
 render();if(S.profile&&S.tx.length&&(!S.lastBk||S.lastBk<ds(30)))$('#ban').innerHTML='<div class="msg">Hace más de 30 días que no descargas una copia de seguridad. <button data-a="tab" data-i="set">Ir a Ajustes</button></div>'})();
